version: "3"

services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db1
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  metabase:
    image: metabase/metabase
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      # https://www.metabase.com/docs/latest/operations-guide/environment-variables.html
      MB_DB_FILE: /metabase-data/metabase.db
      MB_ADMIN_EMAIL: admin@pouet.fr
      MB_ANON_TRACKING_ENABLED: "false"
      MB_APPLICATION_LOGO_URL: logo.jpeg
      MB_APPLICATION_NAME: metabase-test
      MB_EMAIL_FROM_ADDRESS: admin@pouet.fr
      MB_ENABLE_EMBEDDING: "true"
      MB_ENABLE_PUBLIC_SHARING: "true"
      MB_ENCRYPTION_SECRET_KEY: UkYerMHBcbwnoGpSJ0sj
      MB_SITE_LOCALE: fr
      MB_SITE_NAME: Super dashboard
    ports:
      - 3030:3000
